// Curated fictional activities for interaction demos; no live event or weather claims.
export const activities = [
  {
    id: "lake",
    title: "沿着西湖，把步子放慢",
    subtitle: "湖边漫步 · 收集一整个下午的风",
    category: "城市漫步",
    cost: 0,
    duration: 120,
    distance: 4.2,
    indoor: false,
    area: "西湖东岸",
    image: "lake.jpg",
    tag: "零元出逃",
    capacity: 8,
    desc: "从湖滨步道出发，沿湖散步、拍照，在树荫下休息。建议穿舒适的鞋，带好饮水。此路线为示例，请出行前核对开放情况。",
  },
  {
    id: "gallery",
    title: "在美术馆，偶遇一种颜色",
    subtitle: "慢慢看展 · 给灵感充个电",
    category: "展览艺术",
    cost: 30,
    duration: 90,
    distance: 3.1,
    indoor: true,
    area: "南山路片区",
    image: "gallery.jpg",
    tag: "雨天也能去",
    capacity: 6,
    desc: "用一个半小时观看绘画与装置，记下最喜欢的作品。展览名称、票价均为演示设定，不对应当前售票活动。",
  },
  {
    id: "coffee",
    title: "找一家小店，把下午留白",
    subtitle: "咖啡与阅读 · 和朋友坐一会儿",
    category: "美食咖啡",
    cost: 35,
    duration: 60,
    distance: 2.5,
    indoor: true,
    area: "南山路片区",
    image: "coffee.jpg",
    tag: "两个人刚刚好",
    capacity: 4,
    desc: "挑一个靠窗的位置，点一杯饮品，读书或聊天。消费为人均估算，具体门店请自行确认。",
  },
  {
    id: "market",
    title: "在周末市集，淘一点快乐",
    subtitle: "手作小物 · 不赶时间的闲逛",
    category: "市集手作",
    cost: 20,
    duration: 90,
    distance: 3.8,
    indoor: false,
    area: "湖滨片区",
    image: "market.jpg",
    tag: "小预算大满足",
    capacity: 8,
    desc: "逛手作摊位、交换创意灵感。此为示例市集，不代表当地本周末正在举办活动，预算不包含额外购物。",
  },
  {
    id: "music",
    title: "让一场小演出结束这一天",
    subtitle: "原声音乐 · 好好听一首歌",
    category: "音乐演出",
    cost: 80,
    duration: 90,
    distance: 5.1,
    indoor: true,
    area: "武林片区",
    image: "music.jpg",
    tag: "周末有点声音",
    capacity: 4,
    desc: "小型原声演出概念活动，展示演出类推荐流程。并无真实售票场次，费用为演示值。",
  },
  {
    id: "hike",
    title: "向山里走，换一口新鲜空气",
    subtitle: "轻徒步 · 走进绿色的周末",
    category: "户外徒步",
    cost: 10,
    duration: 150,
    distance: 7.6,
    indoor: false,
    area: "玉皇山周边",
    image: "hike.jpg",
    tag: "给自己放个风",
    capacity: 8,
    desc: "轻徒步示例路线，含休息时间。下雨时不推荐；实际路线、路况和开放情况须出发前确认。",
  },
];
export const categories = [
  "全部灵感",
  "城市漫步",
  "展览艺术",
  "美食咖啡",
  "市集手作",
  "音乐演出",
  "户外徒步",
];
